### ISSUE TITLE
will the IRIs be dereferencible?

### ISSUE THREAD

**Issue by egonw** [springernature/scigraph#1]
That is, if I open, e.g. http://www.springernature.com/scigraph/things/journal-brands/ec761180bff4f7276190f23adb4e74f9, will get RDF returned (possible after content negotiation)?

**Comment by lambdamusic** [comment]
Hi (again) - yes that's something we haven't implemented yet but have already [announced](https://lists.w3.org/Archives/Public/semantic-web/2017Mar/0039.html) our intention to support it.

Thanks for the feedback!
